# Site settings
title: TECHculture
email: jennifer.a.miller2@.com
description: "Description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: FakeJennMiller
github_username:  JennMiller

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
highlighter: Pygments
encoding: utf-8
