# Site settings
title: Jenn Miller
email: jennifer.a.miller2@.com
description: "Create, explore, learn."
baseurl: ""
url: 
twitter_username: FakeJennMiller
github_username:  JennMiller

# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
highlighter: Pygments
encoding: utf-8
